name: Automated Deployment Pipeline
run-name: ADP
on:
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Source Branch
        uses: actions/checkout@v4
        with:
         path: main
         ref: main
      - name: Checkout Deployment Branch
        uses: actions/checkout@v4
        with:
          repository: p-seminar-lg/p-seminar-lg.github.io
          path: site
          ref: site
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Installing Astro
        run: npm install astro
      - name: Building website
        run: npm run build
      - name: LS
        run: ls

